pipeline{
    agent any
    environment {
    PATH = "/opt/apache-maven-3.8.1/bin:$PATH"
    }
    stages{
        stage("hello"){
            steps{
                git branch: 'main', credentialsId: '1cc302f7-6af9-419e-8334-5a1a772cf0e9', url: 'https://github.com/govardhan414/devops.git'
            }
        }
         stage("build"){
            steps{
                sh "mvn clean install"
            }
        
        }
        stage("deploy"){
            steps{
               sshagent(['ec2-user']) {
               sh "scp -o StrictHostKeyChecking=no webapp/target/webapp.war ec2-user@13.126.93.213:/opt/apache-tomcat-8.5.69/webapps"
               }
            }
        
        }
    }
}
